services:
  - type: web
    name: survey-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    plan: free
    branch: main
    autoDeploy: true
