# Generated by Django 5.2.3 on 2025-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='العمر'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='نبذة عنك'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الأطفال'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('damascus', 'دمشق'), ('aleppo', 'حلب'), ('homs', 'حمص'), ('hama', 'حماة'), ('latakia', 'اللاذقية'), ('tartous', 'طرطوس'), ('daraa', 'درعا'), ('sweida', 'السويداء'), ('deir-ezzor', 'دير الزور'), ('raqqa', 'الرقة'), ('idlib', 'إدلب'), ('hasakeh', 'الحسكة'), ('quneitra', 'القنيطرة'), ('rural-damascus', 'ريف دمشق'), ('other', 'أخرى')], max_length=50, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('none', 'دون تعليم'), ('primary', 'ابتدائي'), ('middle', 'إعدادي'), ('highschool', 'ثانوي'), ('diploma', 'معهد'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=20, verbose_name='المستوى التعليمي'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='حالة العمل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد أفراد الأسرة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاسم الكامل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_issues',
            field=models.TextField(blank=True, verbose_name='مشاكل صحية إن وجدت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income',
            field=models.CharField(blank=True, choices=[('none', 'لا يوجد دخل'), ('<100k', 'أقل من 100 ألف ل.س'), ('100k-300k', 'بين 100 ألف - 300 ألف ل.س'), ('300k-600k', 'بين 300 ألف - 600 ألف ل.س'), ('>600k', 'أكثر من 600 ألف ل.س')], max_length=50, verbose_name='متوسط الدخل الشهري'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, verbose_name='الاهتمامات الشخصية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'أعزب / عزباء'), ('married', 'متزوج / متزوجة'), ('divorced', 'مطلّق / مطلّقة'), ('widowed', 'أرمل / أرملة')], max_length=10, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='الحي / المنطقة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='المهنة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الموبايل'),
        ),
    ]
