# Generated by Django 5.2.4 on 2025-07-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'إجابة نصية'), ('radio', 'اختيار واحد'), ('checkbox', 'اختيارات متعددة'), ('number', 'رقمي'), ('yesno', 'نعم / لا'), ('scale', 'مقياس')], default='text', max_length=20),
        ),
    ]
